name: Deploying to Containers
on: [push, workflow_dispatch]
env:
    MONGODB_DB_NAME: gh-actions-docker
jobs:
    test:
        environment: test #environment created in GitHub
        env:
            MONGODB_CONNECTION_PROTOCOL: mongodb+srv
            MONGODB_CLUSTER_ADDRESS: cluster0.tjcxjtz.mongodb.net
            # MONGODB_USERNAME: gbandarudevops
            # MONGODB_PASSWORD: NQkLSelXmGMzYs6M
            MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }} #SECRETS CREATED IN ENVIRONMENT
            MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }} #SECRETS CREATED IN ENVIRONMENT
            PORT: 8080
        runs-on: ubuntu-latest
        container:
            image: node:16            
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4.1.1
            - name: cache dependencies
              uses: actions/cache@v4.0.1
              with:
                path: ~/.npm
                key: npm-dep-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Run Server
              run: npm start & npx wait-on http://127.0.0.1:$PORT
            - name: Run Tests
              run: npm test
            - name: Output Information
              run: |
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: |
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
                echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"


