name: Deploying to Containers
on: [push, workflow_dispatch]
env:
    MONGODB_DB_NAME: gh-actions-docker
jobs:
    test:
        environment: test #environment created in GitHub
        #as per services environment
        env:
            MONGODB_CONNECTION_PROTOCOL: mongodb
            MONGODB_CLUSTER_ADDRESS: mongodb
            MONGODB_USERNAME: root
            MONGODB_PASSWORD: example
            PORT: 8080
        runs-on: ubuntu-latest
        container:
            image: node:16
        #Adding Service Containers to spinup environment for testing purpose
        services:
            mongodb:
                image: mongo:latest
                env:
                    MONGO_INITDB_ROOT_USERNAME: root
                    MONGO_INITDB_ROOT_PASSWORD: example

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4.1.1
            - name: cache dependencies
              uses: actions/cache@v4.0.1
              with:
                path: ~/.npm
                key: npm-dep-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Run Server
              run: npm start & npx wait-on http://127.0.0.1:$PORT
            - name: Run Tests
              run: npm test
            - name: Output Information
              run: |
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: |
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
                echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"


